import { test, expect } from "@playwright/test"

test.beforeEach(async ({ page }) => {
  await page.route("**/*", route => {
    const url = new URL(route.request().url())
    if (url.hostname === "127.0.0.1") return route.continue()
    if (url.hostname === "script.google.com") return route.fulfill({ json: { totalViews: 8, pages: {}, daily: [] } })
    return route.abort()
  })
})

for (const collapsed of [false, true]) {
  test(`shortcuts open from More and the question-mark key: ${collapsed ? "collapsed" : "expanded"}`, async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto("/")
    if (collapsed) await page.getByRole("button", { name: "사이드바 접기", exact: true }).click()
    const footer = page.locator('[data-slot="sidebar-footer"]')
    await expect(footer.getByRole("button")).toHaveCount(4)
    await expect(footer.getByRole("button", { name: "단축키", exact: true })).toHaveCount(0)
    const more = page.getByRole("button", { name: "블로그 정보 더보기", exact: true })
    await more.click()
    const menu = page.getByRole("menu", { name: "블로그 정보 더보기", exact: true })
    await menu.getByRole("menuitem", { name: "단축키", exact: true }).click()
    const guide = page.getByRole("dialog", { name: "단축키", exact: true })
    await expect(guide).toBeVisible()
    await expect(guide.getByText("검색 열기", { exact: true })).toBeVisible()
    await expect(menu).toBeHidden()
    await page.keyboard.press("Escape")
    await expect(guide).toBeHidden()
    await expect(more).toBeFocused()
    await page.keyboard.press("?")
    await expect(guide).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(guide).toBeHidden()
    await more.click()
    await page.keyboard.press("?")
    await expect(guide).toBeVisible()
    await expect(menu).toBeHidden()
  })
}

test("mobile More closes the drawer before showing the shortcuts dialog", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto("/")
  const openMenu = page.getByRole("button", { name: "메뉴 열기", exact: true })
  await openMenu.click()
  const drawer = page.locator('[data-mobile="true"]')
  await expect(drawer.locator('[data-slot="sidebar-footer"]').getByRole("button")).toHaveCount(4)
  await drawer.getByRole("button", { name: "블로그 정보 더보기", exact: true }).click()
  await page.getByRole("menuitem", { name: "단축키", exact: true }).click()
  const guide = page.getByRole("dialog", { name: "단축키", exact: true })
  await expect(guide).toBeVisible()
  await expect(drawer).toBeHidden()
  await expect(page.getByRole("dialog")).toHaveCount(1)
  await page.keyboard.press("Escape")
  await expect(guide).toBeHidden()
  await expect(openMenu).toBeFocused()
  await page.keyboard.press("?")
  await expect(guide).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
})
